config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :new, :create, :show]
  resources :groups, only: [:index, :show]
  resources :weapons, only: [:index, :update]
  resources :supplies, only: [:index, :show]
  resources :owned_items, only: [:destroy]
  
  get '/zombie', to: 'users#edit'
  root 'application#hello'
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

  delete '/logout' => 'sessions#destroy'
  post '/logout' => 'sessions#destroy'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true



end

app/models/group.rb
class Group < ApplicationRecord
	has_many :users
	has_many :weapons, through: :users
	has_many :owned_items, through: :users
	has_many :supplies, through: :owned_items

	validates :name, presence: true
	validates :name, uniqueness: true

	def readiness
		supply_score + weapon_score
	end 

	def supply_score 
		readiness_score = 0
		self.users.each do |user|
			user.supplies.each do |supply|
				readiness_score += supply.readiness_value 
			end 
		end 
		readiness_score / self.users.count
	end 

	def weapon_score
		weapon_score = 0
		self.users.each do |user|
			user.weapons.each do |weapon|
				weapon_score += weapon.readiness_value
			end 
		end 
		return weapon_score
	end 

end

app/models/owned_item.rb
class OwnedItem < ApplicationRecord
	belongs_to :user
	belongs_to :supply
	has_one :weapon, through: :user
	has_one :group, through: :user
	
	validates :user_id, presence: true
	validates :user_id, numericality: { only_integer: true }
	validates :supply_id, presence: true
	validates :supply_id, numericality: { only_integer: true }
	
end

app/models/supply.rb
class Supply < ApplicationRecord
	has_many :owned_items
	has_many :users, through: :owned_items
	has_many :groups, through: :users
	has_many :weapons, through: :users
	
	validates :name, presence: true
	validates :name, uniqueness: true
	validates :readiness_value, presence: true
	validates :readiness_value, numericality: { only_integer: true }
	
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :name, presence: true
	validates :name, uniqueness: true
	validates :group_id, presence: true
	validates :group_id, numericality: { only_integer: true }

	belongs_to :group
	has_many :weapons
	has_many :owned_items
	has_many :supplies, through: :owned_items


	
end

app/models/weapon.rb
class Weapon < ApplicationRecord
	belongs_to :user, optional: true
	has_one :group, through: :user
	has_many :owned_items, through: :user
	has_many :supplies, through: :owned_items

	validates :name, presence: true
	validates :name, uniqueness: true
	validates :user_id, numericality: { only_integer: true }, allow_nil: true
	validates :readiness_value, presence: true
	validates :readiness_value, numericality: { only_integer: true }
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

    def hello 
        redirect_to controller: 'sessions', action: 'new' unless session[:user_id]
        @supplies = Supply.all
        @owned_items = OwnedItem.all
      end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController 
    before_action :require_login

    def index
        @groups = Group.all
    end

    def show
        @group = Group.find(params[:id])
        @score = @group.readiness
    end

    private 

    def require_login
       
        return head(:forbidden) unless session.include? :user_id
    end


end

app/controllers/owned_items_controller.rb
class OwnedItemsController < ApplicationController

    def destroy 
        @item = OwnedItem.find(params[:id])
        user = @item.user
        @item.destroy
        redirect_to user_path(user)
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include SessionsHelper
    before_action :authorize!, except: [:new, :create]

    def new
        if session[:user_id] 
            p session[:user_id]
            redirect_to '/'
        end

    end

    def create 
        @user = User.find_by(name: params[:name])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to(controller: 'application', action: 'hello' )
        else
            flash[:message] = "You Don't Belong Here!"
            redirect_to '/login'
        end
       
    end

    def destroy
        
        session.delete :user_id
        redirect_to '/login'
    end

    


end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController 

    def index
        @supplies = Supply.all
    end

    def show 
        @supply = Supply.find(params[:id])
    end 


end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
    include SessionsHelper

    def index
        @users = User.all.page(params[:page])
    end

    def new
        @user = User.new
        @weapons = Weapon.all.select {|weapon| weapon.user_id == nil}
    end

    def create
        @user = User.new(user_params)
        if @user.valid?
            @user.save
            @weapon = Weapon.find(params[:user][:weapon_ids])
            @weapon.update(user_id: @user.id)
            params[:user][:supply_ids].each do |supply_id|
                OwnedItem.create(user_id: @user.id, supply_id: supply_id)
            end 
            session[:user_id] = @user.id
            redirect_to user_path(@user)
            # @owned_item = OwnedItem.new(user_id: @user.id, supply_id: params[:id])
        else
            @weapons = Weapon.all.select {|weapon| weapon.user_id == nil}
            render :new   
        end
    end

    def show
        if session[:user_id]
            @current_user = User.find(session[:user_id])
        end
        @user = User.find(params[:id])
    end

    def edit

    end 



    private
    
    def user_params
        params.require(:user).permit(:name, :password, :group_id)
    end

    # def supply_params
    #     params.require(:user).permit(:supply_ids)
    # end 

    # def weapon_params
    #     params.require(:user).permit(:weapon_ids)
    # end 

end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController 

    def index 
        @weapons = Weapon.all.select {|weapon| weapon.user_id == nil }
        @taken = Weapon.all.select {|weapon| weapon.user_id != nil }
        @taken_weapons = Kaminari.paginate_array(@taken).page(params[:page]).per(10)
    end

    def update
        @weapon = Weapon.find(params[:id])
        @user = User.find(session[:user_id])
        @weapon.update(user_id: @user.id)
        redirect_to user_path(@user)
    end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owned_items_helper.rb
module OwnedItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def logged_in?
        !!current_user
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        end
    end


    def authorize!
        redirect_to '/login' unless logged_in?
    end




end

app/views/application/hello.html.erb
<h1>Hello <%= current_user.name %></h1>
<% range = (1..14).to_a %>
<%=image_tag("test_#{range.sample}.png")%>

<h3>You posess the following: <% current_user.owned_items.each do |owned_item| %></h3>
<p><%= @supplies.find_by(id: owned_item.supply_id).name.downcase %></p>
<% end %>
<% current_user.weapons.each do |weapon| %></h3>
<p><%= weapon.name %></p>
<% end %>
<!--  <%= form_tag ({controller: 'sessions', action: 'destroy', method: 'POST'}) do %>
    <input type=submit value='logout'>
<%end %>

<!-- <%= button_to "Logout", logout_path, method: :delete %> -->

app/views/groups/index.html.erb
<h1>The Contingents of ZARA</h1>

<ul>
    <% @groups.each do |group| %>
    <li>
        <%= link_to group.name, group_path(group) %>
    </li>
    <%end%>
</ul>

app/views/groups/show.html.erb
<h1>The Contingent of <%= @group.name %></h1>

<h2>Readiness Score: <%= @score %> </h2>
Members:
<ul>
<%@group.users.each do |member| %> 
<li>
    <%= link_to member.name, user_path(member) %>
</li>
    <%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZombieReadinessApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      ul.breadcrumb {
        padding: 8px 16px;
        list-style: none;
        background-color: #eee;
      }

      ul.breadcrumb li {display: inline;}

      ul.breadcrumb li+li:before {
        padding: 8px;
        color: black;
        content: "/\00a0";
      }

      ul.breadcrumb li a {color: green;}
    </style>
  </head>

  <body>
    
    <% if !!session[:user_id] %>
    <ul class="breadcrumb">
        <li><%= link_to "humans", users_path if session[:user_id] %></li>
        <li><%= link_to "contingents", groups_path if session[:user_id] %></li>
        <li><%= link_to "weapons", weapons_path if session[:user_id] %></li>
        <li><%= link_to "supplies", supplies_path if session[:user_id] %></li>
        <li><%= link_to "your profile", user_path(User.find(session[:user_id])) if session[:user_id] %></li>
        <li><%= link_to "log out", logout_path, method: :delete if session[:user_id] %></li>
    </ul>
    <%end%>

    <%= yield %>

    <% if !!session[:user_id] %>
    <ul class="breadcrumb">
      <li><%= link_to "humans", users_path if session[:user_id] %></li>
      <li><%= link_to "contingents", groups_path if session[:user_id] %></li>
      <li><%= link_to "weapons", weapons_path if session[:user_id] %></li>
      <li><%= link_to "supplies", supplies_path if session[:user_id] %></li>
      <li><%= link_to "your profile", user_path(User.find(session[:user_id])) if session[:user_id] %></li>
      <li><%= link_to "log out", logout_path, method: :delete if session[:user_id] %></li>
  </ul>
  <%end%>
  
  </body>
</html>

app/views/supplies/index.html.erb
<h1>All the Stuff</h1>
<ul>
    <% @supplies.each do |supply| %> 
    <li><%= link_to supply.name, supply_path(supply) %></li>
    <%end%>
</ul>

app/views/supplies/show.html.erb
<h1><%= @supply.name %> </h1>

<h2>Readiness Value: <%= @supply.readiness_value %></h2>

app/views/users/edit.html.erb
<%= image_tag("Zombie.jpg", height: "725", width: "1450")%> 

app/views/users/index.html.erb
<h1>Directory of Humans</h1>
<%= paginate @users %>
<br>
<p><% @users.each do |user| %></p>
<h3>Name: <%= link_to user.name, user_path(user) %></h3>
<p>Contingent: <%= link_to user.group.name, user.group %></p>
<br />
<% end %>

app/views/users/new.html.erb
<h1>Hi, welcome to the apocolypse!</h1>
<h2>Identify yourself.</h2>

<% if @user.errors %> 
    <ul>
        <% @user.errors.full_messages.each do |error| %> 
        <li><%= error %></li>
        <% end %> 
    </ul>
<% end %> 
<br />
<div class="new user">
<%= form_for @user do |f| %>
<p><% f.label :name %>Your Name:</p>
<h5>(first and last, separated by a space)</h5>
<p><%= f.text_field :name %></p>
<br />
<p><% f.label :password %>Password: </p>
<p><%= f.password_field :password %></p>
<br />
<p><% f.label :group %>Join a Contingent:</p>
<p><%= f.collection_select(:group_id, Group.all, :id, :name) %></p>
<br />
<p><% f.label :weapon %>Select your weapon:</p>
<p><%= f.collection_select(:weapon_ids, @weapons, :id, :name) %></p>
<br />
<p><% f.label :weapon %>Select your supplies:</p>
<p><%= f.collection_check_boxes(:supply_ids, Supply.all, :id, :name) %></p>
<br /><br /> 


<p><%= f.submit "Create" %></p>
<% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% range = (1..14).to_a %>
<%=image_tag("test_#{range.sample}.png")%>


<h2>Contingent: <%= link_to "#{@user.group.name}", group_path(@user.group) %> </h2>

<% if session[:user_id] == @user.id %>
<h4><br>Weapons currently in posession:</h4>
<ul>
    <% @user.weapons.each do |weapon| %>
        <li><%= weapon.name %> (readiness: <%= weapon.readiness_value %>)</li><br>
    <% end %> 
</ul>

<h4>Supplies owned:</h4>
<ul>
    <% @user.owned_items.each do |owneditem| %> 
        <li> <%= owneditem.supply.name %> (readiness: <%= owneditem.supply.readiness_value %>)</li>
        <%= button_to 'Use Item', owned_item_path(owneditem), method: :delete %><br>
    <% end %> 
</ul>

<%= link_to "Fight Zombie", zombie_path %><br>


<% end %> 

app/views/weapons/index.html.erb
<h1>WEAPONS!!!!!</h1>
<ul>
<h2>Available:</h2>
<% @weapons.each do |weapon| %> 
    <li>
        <%= weapon.name %> <br>
        readiness value: <%= weapon.readiness_value %>
    </li>
    <%= button_to 'Pick Up Weapon', weapon_path(weapon), method: :put %>
    <br />
<% end %> 

<br />
<h3>In use:</h3>
<%= paginate @taken_weapons %>
<br>
<br>
<% @taken_weapons.each do |weapon| %> 
    <li>
    <%= weapon.name %><br>
    user: <%= link_to weapon.user.name, user_path(weapon.user) %><br>
    readiness value: <%= weapon.readiness_value %>
    </li>
    <br />
<% end %> 
</ul>
<%= paginate @taken_weapons %>
<br>